# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mandrill_username: <%= ENV["cashflow@rowanshead.com"] %>
  mandrill_api_key: <%= ENV["PXjtf_hKNFbpMs7oRjbSmA"] %>
  mailchimp_api_key: <%= ENV["a376b5eebdd6dcee509d5e00a7e0f1ce-us12"] %>
  mailchimp_list_id: <%= ENV["1123ae14e7"] %>
  domain_name: rowanshead.com
  owner_email: <%= ENV["cashflow@rowanshead.com"] %>
  secret_key_base: 9964fe13289c89fba0b432aaef3c97b32c165168915c57250812794516b61c78790db299a510eb6285cc7b075079f4d678f8f5d90049dc36033b918bab91d056

test:
  secret_key_base: 03dbd4fcae703b202b6244210dd02d056513e06821f346071aa331d260419c69a1e311daea8b681a9572848c2475ec15f2cbe406f0ddd4b19115bf6f449bc056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandrill_username: <%= ENV["cashflow@rowanshead.com"] %>
  mandrill_api_key: <%= ENV["PXjtf_hKNFbpMs7oRjbSmA"] %>
  mailchimp_api_key: <%= ENV["a376b5eebdd6dcee509d5e00a7e0f1ce-us12"] %>
  mailchimp_list_id: <%= ENV["1123ae14e7"] %>
  domain_name: rowanshead.com
  owner_email: <%= ENV["cashflow@rowanshead.com"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
